//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviantArtScrapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviantArtScrapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Button_Settings {
            get {
                return ResourceManager.GetString("Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Scraping.
        /// </summary>
        internal static string Button_StartScraping {
            get {
                return ResourceManager.GetString("Button_StartScraping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        internal static string Button_TestConnection {
            get {
                return ResourceManager.GetString("Button_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        internal static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV files (*.csv)|*.csv.
        /// </summary>
        internal static string Filter_Csv {
            get {
                return ResourceManager.GetString("Filter_Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML files (*.html)|*.html.
        /// </summary>
        internal static string Filter_Html {
            get {
                return ResourceManager.GetString("Filter_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel files (*.xlsx)|*.xlsx.
        /// </summary>
        internal static string Filter_Xlsx {
            get {
                return ResourceManager.GetString("Filter_Xlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Format.
        /// </summary>
        internal static string Label_FileFormat {
            get {
                return ResourceManager.GetString("Label_FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name:.
        /// </summary>
        internal static string Label_FileName {
            get {
                return ResourceManager.GetString("Label_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviantArt Username:.
        /// </summary>
        internal static string Label_Username {
            get {
                return ResourceManager.GetString("Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Configured - Authentication required.
        /// </summary>
        internal static string MainForm_StatusConfigured {
            get {
                return ResourceManager.GetString("MainForm_StatusConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Not configured - Please configure API settings.
        /// </summary>
        internal static string MainForm_StatusNotConfigured {
            get {
                return ResourceManager.GetString("MainForm_StatusNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Ready - API configured and authenticated.
        /// </summary>
        internal static string MainForm_StatusReady {
            get {
                return ResourceManager.GetString("MainForm_StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviantArt Scrapper.
        /// </summary>
        internal static string MainForm_Title {
            get {
                return ResourceManager.GetString("MainForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraping was cancelled before any favorites were collected..
        /// </summary>
        internal static string Message_CancelledNoFavorites {
            get {
                return ResourceManager.GetString("Message_CancelledNoFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraping was cancelled before any items were collected..
        /// </summary>
        internal static string Message_CancelledNoItems {
            get {
                return ResourceManager.GetString("Message_CancelledNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraping was cancelled after collecting {0} items.
        ///
        ///Would you like to export the partial results?.
        /// </summary>
        internal static string Message_CancelledPartial {
            get {
                return ResourceManager.GetString("Message_CancelledPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraping was cancelled after collecting {0} favorites.
        ///
        ///Would you like to export the partial results?.
        /// </summary>
        internal static string Message_CancelledPartialFavorites {
            get {
                return ResourceManager.GetString("Message_CancelledPartialFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure your API credentials in Settings first..
        /// </summary>
        internal static string Message_ConfigureApi {
            get {
                return ResourceManager.GetString("Message_ConfigureApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a filename..
        /// </summary>
        internal static string Message_EnterFilename {
            get {
                return ResourceManager.GetString("Message_EnterFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a DeviantArt username..
        /// </summary>
        internal static string Message_EnterUsername {
            get {
                return ResourceManager.GetString("Message_EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorites found for user &apos;{0}&apos;..
        /// </summary>
        internal static string Message_NoFavorites {
            get {
                return ResourceManager.GetString("Message_NoFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gallery items found for user &apos;{0}&apos;..
        /// </summary>
        internal static string Message_NoGalleryItems {
            get {
                return ResourceManager.GetString("Message_NoGalleryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported {0} items.
        ///
        ///{1}.
        /// </summary>
        internal static string Message_PartialExported {
            get {
                return ResourceManager.GetString("Message_PartialExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial results exported to {0}.
        /// </summary>
        internal static string Message_PartialExportedFile {
            get {
                return ResourceManager.GetString("Message_PartialExportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial results exported to HTML ({0} page(s)).
        /// </summary>
        internal static string Message_PartialExportedHtml {
            get {
                return ResourceManager.GetString("Message_PartialExportedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting partial results: {0}.
        /// </summary>
        internal static string Message_PartialExportError {
            get {
                return ResourceManager.GetString("Message_PartialExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during scraping: {0}.
        /// </summary>
        internal static string Message_ScrapingError {
            get {
                return ResourceManager.GetString("Message_ScrapingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraping is already in progress..
        /// </summary>
        internal static string Message_ScrapingInProgress {
            get {
                return ResourceManager.GetString("Message_ScrapingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully scraped {0} items and exported to {1}.
        /// </summary>
        internal static string Message_SuccessScraped {
            get {
                return ResourceManager.GetString("Message_SuccessScraped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully scraped {0} favorites and exported to {1}.
        /// </summary>
        internal static string Message_SuccessScrapedFavorites {
            get {
                return ResourceManager.GetString("Message_SuccessScrapedFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully scraped {0} favorites and exported to {1} HTML page(s).
        /// </summary>
        internal static string Message_SuccessScrapedFavoritesHtml {
            get {
                return ResourceManager.GetString("Message_SuccessScrapedFavoritesHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully scraped {0} items and exported to {1} HTML page(s).
        /// </summary>
        internal static string Message_SuccessScrapedHtml {
            get {
                return ResourceManager.GetString("Message_SuccessScrapedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string MessageBox_Cancelled {
            get {
                return ResourceManager.GetString("MessageBox_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Required.
        /// </summary>
        internal static string MessageBox_ConfigRequired {
            get {
                return ResourceManager.GetString("MessageBox_ConfigRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBox_Error {
            get {
                return ResourceManager.GetString("MessageBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Complete.
        /// </summary>
        internal static string MessageBox_ExportComplete {
            get {
                return ResourceManager.GetString("MessageBox_ExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Error.
        /// </summary>
        internal static string MessageBox_ExportError {
            get {
                return ResourceManager.GetString("MessageBox_ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MessageBox_Information {
            get {
                return ResourceManager.GetString("MessageBox_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results.
        /// </summary>
        internal static string MessageBox_NoResults {
            get {
                return ResourceManager.GetString("MessageBox_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Export Complete.
        /// </summary>
        internal static string MessageBox_PartialComplete {
            get {
                return ResourceManager.GetString("MessageBox_PartialComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Partial Results?.
        /// </summary>
        internal static string MessageBox_PartialExport {
            get {
                return ResourceManager.GetString("MessageBox_PartialExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MessageBox_Success {
            get {
                return ResourceManager.GetString("MessageBox_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string MessageBox_ValidationError {
            get {
                return ResourceManager.GetString("MessageBox_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        internal static string Progress_Cancelling {
            get {
                return ResourceManager.GetString("Progress_Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collected {0} items....
        /// </summary>
        internal static string Progress_Collected {
            get {
                return ResourceManager.GetString("Progress_Collected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collected {0} favorites....
        /// </summary>
        internal static string Progress_CollectedFavorites {
            get {
                return ResourceManager.GetString("Progress_CollectedFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Progress_Complete {
            get {
                return ResourceManager.GetString("Progress_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred.
        /// </summary>
        internal static string Progress_Error {
            get {
                return ResourceManager.GetString("Progress_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export complete!.
        /// </summary>
        internal static string Progress_ExportComplete {
            get {
                return ResourceManager.GetString("Progress_ExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting data....
        /// </summary>
        internal static string Progress_Exporting {
            get {
                return ResourceManager.GetString("Progress_Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string Progress_Initializing {
            get {
                return ResourceManager.GetString("Progress_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed (attempt {0}/{1}), retrying in {2}ms....
        /// </summary>
        internal static string Progress_RequestFailed {
            get {
                return ResourceManager.GetString("Progress_RequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraping....
        /// </summary>
        internal static string Progress_Scraping {
            get {
                return ResourceManager.GetString("Progress_Scraping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Settings.
        /// </summary>
        internal static string Settings_ApiSettings {
            get {
                return ResourceManager.GetString("Settings_ApiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Status.
        /// </summary>
        internal static string Settings_AuthStatus {
            get {
                return ResourceManager.GetString("Settings_AuthStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID:.
        /// </summary>
        internal static string Settings_ClientId {
            get {
                return ResourceManager.GetString("Settings_ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret:.
        /// </summary>
        internal static string Settings_ClientSecret {
            get {
                return ResourceManager.GetString("Settings_ClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection test failed: {0}.
        /// </summary>
        internal static string Settings_ConnectionFailed {
            get {
                return ResourceManager.GetString("Settings_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successful!.
        /// </summary>
        internal static string Settings_ConnectionSuccess {
            get {
                return ResourceManager.GetString("Settings_ConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter both Client ID and Client Secret..
        /// </summary>
        internal static string Settings_EnterCredentials {
            get {
                return ResourceManager.GetString("Settings_EnterCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load configuration: {0}.
        /// </summary>
        internal static string Settings_LoadFailed {
            get {
                return ResourceManager.GetString("Settings_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No token available.
        /// </summary>
        internal static string Settings_NoToken {
            get {
                return ResourceManager.GetString("Settings_NoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully!.
        /// </summary>
        internal static string Settings_SavedSuccess {
            get {
                return ResourceManager.GetString("Settings_SavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save settings: {0}.
        /// </summary>
        internal static string Settings_SaveFailed {
            get {
                return ResourceManager.GetString("Settings_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Configuration.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Status:.
        /// </summary>
        internal static string Settings_TokenStatus {
            get {
                return ResourceManager.GetString("Settings_TokenStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until {0}.
        /// </summary>
        internal static string Settings_TokenValid {
            get {
                return ResourceManager.GetString("Settings_TokenValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings - DeviantArt Scrapper.
        /// </summary>
        internal static string Settings_WindowTitle {
            get {
                return ResourceManager.GetString("Settings_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Tab_Favorites {
            get {
                return ResourceManager.GetString("Tab_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string Tab_Gallery {
            get {
                return ResourceManager.GetString("Tab_Gallery", resourceCulture);
            }
        }
    }
}
